export { default as H1 } from './H1/H1';
export { default as H2 } from './H2/H2';
export { default as H3 } from './H3/H3';
export { default as H4 } from './H4/H4';
export { default as H5 } from './H5/H5';
export { default as H6 } from './H6/H6';
export { default as P1 } from './P1/P1';
export { default as P2 } from './P2/P2';
export { default as Button } from './Button/Button';
export { default as Logo } from './Logo/Logo';
export { default as Tags } from './Tags/Tags';
export { default as Thumbnail } from './Thumbnail/Thumbnail';
export { default as Avatar } from './Avatar/Avatar';
// export { default as UNTextField } from './UNTextField/UNTextField';
