export const courseTypes = {
  UPDATE_COURSES: 'UPDATE_COURSES',
  FETCH_FREE_COURSES: 'FETCH_FREE_COURSES',
  FETCH_FREE_GOAL_COURSES: 'FETCH_FREE_GOAL_COURSES'
};

export const educatorTypes = {
  UPDATE_USERS: 'UPDATE_USERS',
  FETCH_EDUCATOR_LEADERBOARD: 'FETCH_EDUCATOR_LEADERBOARD',
  FETCH_FOLLOWING_LIST: 'FETCH_FOLLOWING_LIST',
  FETCH_PROFILE_INFO: 'FETCH_PROFILE_INFO'
};

export const goalTypes = {
  UPDATE_GOALS: 'UPDATE_GOALS'
};

export const drawerTypes = {
  OPEN_DRAWER: 'OPEN_DRAWER',
  CLOSE_DRAWER: 'CLOSE_DRAWER'
};
