export const courseTypes = {
  UPDATE_COURSES: 'UPDATE_COURSES',
  FETCH_FREE_COURSES: 'FETCH_FREE_COURSES',
  FETCH_FREE_GOAL_COURSES: 'FETCH_FREE_GOAL_COURSES'
};

export const educatorTypes = {
  UPDATE_USERS: 'UPDATE_USERS',
  FETCH_EDUCATOR_LEADERBOARD: 'FETCH_EDUCATOR_LEADERBOARD',
  FETCH_FOLLOWING_LIST: 'FETCH_FOLLOWING_LIST'
};

export const goalTypes = {
  UPDATE_GOALS: 'UPDATE_GOALS'
};
